### ISSUE TITLE
SteamVR: HTC HMDs camera is not recognized on any USB port.

### ISSUE THREAD

**Issue by KWS-Compat** [ValveSoftware/VR-Community-Bugs#93]
When the user attempts to enable the HMD's camera in the SteamVR Settings, a message is displayed indicating that the camera is not available since it is not recognized by any USB port. Following the suggestion on the camera menu, the user switches the USB device to different USB ports (both 2.0 and 3.0). However, the issue still persists.

![steamvr - unrecognized camera](https://user-images.githubusercontent.com/41118265/50695450-b726c700-100a-11e9-8a29-990d661f85fd.jpg)

Repro Steps:
1. Launch SteamVR.
2. Launch SteamVR Settings from SteamVR Status window.
3. Navigate to Camera tab. Observe the message displayed on the menu.
4. Proceed to switch the USB device to different USB ports.
5. Repeat step 1 to step 3.

Note:
If the Camera is already enabled, please disable it and follow the repro steps.

Repro Rate: 10/10

Expected Result:
The HMD's camera is recognized on any USB port.

Actual Result:
The HMD's camera is not recognized on any USB ports (both USB 2.0 and USB 3.0 ports).

Config Details:
The issue occurs on all configs.
Affected HMDs:
HTC Vive and HTC Vive Pro

SteamVR Beta Build: 1.2.5
Does not occur on SteamVR Stable Build

**Comment by kisak-valve** [comment]
Also reported at https://github.com/ValveSoftware/SteamVR-for-Linux/issues/169.

**Comment by BPHardware** [comment]
Appears to have been pushed to stable 1.2.7 - a number of users are reporting this issue in tickets and on the forums. 

Issue seems to be related to camera config file entries - if the camera entries existed prior to the change, the camera can still be detected in the settings menu and used in SteamVR.

If the camera related entries are not in the config file, the SteamVR settings menu fails to detect the camera and prevents the user from enabling it. Camera related log entries provided by users in this situation indicate that the camera USB device is found by the lighthouse driver, but is disabled due to settings. 

As a result, it may be necessary to manually delete this config file entry to reproduce the problem.

Adding the camera config file entry manually resolves the issue per the SteamVR for linux issue noted above.

**Comment by KWS-Compat** [comment]
Issue was observed to no longer occur as of SteamVR Beta Build 1.2.8
